mysite/blog/urls.py
from blog.views import (BlogListView, CreateBlogView, DeleteBlogView,
                        DetailBlogView, EditBlogView)
from django.urls import path

app_name = "blog"

urlpatterns = [
    path("list/", BlogListView.as_view(), name="list"),
    path("create/", CreateBlogView.as_view(), name="create"),
    path("<slug>/", DetailBlogView.as_view(), name="detail"),
    path("<slug>/edit/", EditBlogView.as_view(), name="edit"),
    path("<slug>/delete/", DeleteBlogView.as_view(), name="delete"),
]

mysite/catalogue/urls.py
from django.urls import path
from catalogue.views import (
    DetailDocumentView,
    CreateDocumentView,
    EditDocumentView,
    CatalogueView,
    DeleteDocumentView,
    DocumentsImageView,
)

app_name = 'catalogue'

urlpatterns = [
    path('list/', CatalogueView.as_view(), name="list"),
    path('create/', CreateDocumentView.as_view(), name="create"),
    path('<slug>/', DetailDocumentView.as_view(), name="detail"),
    path('<slug>/edit/', EditDocumentView.as_view(), name="edit"),
    path('<slug>/delete/', DeleteDocumentView.as_view(), name="delete"),
    path('<slug>/image/', DocumentsImageView.as_view(), name="image"),

]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from personal.views import HomePageView  # home_screen_view

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("admin/", admin.site.urls),
    path("personal/", include("personal.urls", "personal")),
    path("account/", include("account.urls", "account")),
    path("blog/", include("blog.urls", "blog")),
    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path(
        "password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="registration/password_change_done.html"
        ),
        name="password_change_done",
    ),
    path(
        "password_change/",
        auth_views.PasswordChangeView.as_view(
            template_name="registration/password_change.html"
        ),
        name="password_change",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="registration/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/", auth_views.PasswordResetView.as_view(), name="password_reset"
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="registration/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/catalogue/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.conf import settings
from django.db.models.signals import post_delete
from django.dispatch import receiver
from mysite.settings import MEDIA_ROOT
import uuid
import os


def upload_location(instance, filename):
    file_path = 'catalogue/{author_id}/{title}-{filename}'.format(
                author_id=str(instance.author.id), title=str(instance.id), filename=filename)
    return file_path


class Document(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    titre = models.CharField(max_length=100, null=False, blank=False)
    image = models.ImageField(upload_to=upload_location, null=False, blank=False)
    no_inventaire = models.CharField(max_length=100, null=True, blank=True)
    categorie = models.CharField(max_length=100, null=True, blank=True)
    theme = models.CharField(max_length=100, null=True, blank=True)
    technique = models.CharField(max_length=100, null=True, blank=True)
    support = models.CharField(max_length=100, null=True, blank=True)
    region = models.CharField(max_length=100, null=True, blank=True)
    lieu = models.CharField(max_length=100, null=True, blank=True)
    dimensions = models.CharField(max_length=100, null=True, blank=True)
    epoque = models.CharField(max_length=100, null=True, blank=True)
    type_collection = models.CharField(max_length=100, null=True, blank=True)
    droits = models.CharField(max_length=100, null=True, blank=True)

    tags = models.JSONField(default=list, blank=True)
    description = models.TextField(max_length=5000, null=False, blank=True)

    date_published = models.DateTimeField(auto_now_add=True, verbose_name="date published")
    date_updated = models.DateTimeField(auto_now=True, verbose_name="date updated")
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    slug = models.SlugField(blank=True, unique=True)

    def __str__(self):
        return self.titre

    def get_fields(self):
        return [(field.verbose_name, field.value_from_object(self)) for field in self.__class__._meta.fields]


def clean_directory(directory=os.path.join(MEDIA_ROOT, 'catalogue')):
    if os.path.isdir(directory):
        for folder in os.listdir(directory):
            clean_directory(os.path.join(directory, folder))
        if not os.listdir(directory):
            os.rmdir(directory)


@receiver(post_delete, sender=Document)
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False)
    clean_directory()


def pre_save_document_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.author.username + "-" + str(instance.id))


pre_save.connect(pre_save_document_receiver, sender=Document)

mysite/catalogue/forms.py
from django import forms
from catalogue.models import Document


class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ['titre', 'image', 'no_inventaire', 'categorie', 'theme',
                  'technique', 'support', 'region', 'lieu', 'dimensions',
                  'epoque', 'type_collection', 'droits', 'tags', 'description']

mysite/catalogue/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from catalogue.models import Document
from catalogue.forms import DocumentForm
from account.models import Account
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from django.views.generic.base import TemplateView
from .core import extract_catalogue
from django.contrib.auth.decorators import login_required


class CreateDocumentView(LoginRequiredMixin, CreateView):
    form_class = DocumentForm
    template_name = 'catalogue/create_document.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = Account.objects.filter(username=self.request.user.username).first()
        self.object.save()
        return redirect('catalogue:list')


class EditDocumentView(LoginRequiredMixin, UpdateView):
    model = Document
    fields = ['titre', 'description', 'image']
    template_name = 'catalogue/edit_document.html'

    def dispatch(self, request, *args, **kwargs):
        object = self.get_object()
        if request.user != object.author:
            return redirect('catalogue:detail', object.slug)
        return UpdateView.dispatch(self, request, *args, **kwargs)

    def form_valid(self, form):
        self.object = form.save()
        return self.render_to_response(self.get_context_data(form=form))


class DetailDocumentView(DetailView):
    model = Document
    template_name = 'catalogue/detail_document.html'


class DocumentsImageView(DetailView):
    model = Document
    template_name = 'catalogue/image.html'


class CatalogueView(ListView):
    model = Document
    paginate_by = 3
    template_name = 'catalogue/catalogue.html'
    ordering = ['-date_published']

    context_object_name = 'all_search_results'
    searchable_fields = ['titre', 'description', 'no_inventaire', 'categorie', 'theme',
                         'technique', 'support', 'region', 'lieu', 'epoque', 'type_collection',
                         'description']
    specifications = {field: "__icontains" for field in searchable_fields}

    def get_queryset(self):
        result = super(CatalogueView, self).get_queryset()
        filter_query = []
        for field in self.searchable_fields:
            value = self.request.GET.get(field)
            if value:
                filter_query.append(f"Q({field}{self.specifications.get(field)}='{value}')")
        print(filter_query)
        if filter_query:
            result = eval("Document.objects.filter(" + " | ".join(filter_query) + ")")
        else:
            result = Document.objects.all()

        return result

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['show_filter_bar'] = True
        context['searchable_fields'] = self.searchable_fields
        return context

    def post(self, request, *args, **kwargs):
        if request.method == 'POST':
            if request.FILES.get('catalogue'):
                for args in extract_catalogue(request.FILES['catalogue']):
                    args['author'] = request.user
                    object = Document(**args)
                    object.save()
            elif request.POST.get('delete_catalogue'):
                Document.objects.all().delete()
        return redirect('catalogue:list')


class DeleteDocumentView(LoginRequiredMixin, DeleteView):
    model = Document
    success_url = '/catalogue/list'

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

mysite/catalogue/templates/catalogue/catalogue.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<style type="text/css">
  .inputsubmit {
  	width: 0.1px;
  	height: 0.1px;
  	opacity: 0;
  	overflow: hidden;
  	position: absolute;
  	z-index: -1;
  }
</style>

<div class="container">
  {% if request.user.is_authenticated %}
    {% include 'widgets/file_download.html' with input_id='catalogue' %}
    <form id="form_delete_catalogue" method="post" >
      {% csrf_token %}
      <input id="delete_catalogue" name="delete_catalogue" type="submit" class="inputsubmit" value="delete all"
            onclick="return confirm('Etes vous sûr de vouloir supprimer tous les documents du catalogue ?');">
    </form>
  {% endif %}

  <h2 class='title'>Catalogue raisonné
    {% if request.user.is_authenticated %}
      <label class='bs-icon bi bi-x-square' for="delete_catalogue"></label>
      <label class='bs-icon bi bi-images' for="catalogue"></label>
      <a class="bs-icon bi bi-image" href="{% url 'catalogue:create' %}"></a>
    {% endif %}
  </h2>

  {% if all_search_results %}

    {% for object in all_search_results %}
      <a class="btn post mb-1" style="width:100%;" href="{% url 'catalogue:detail' object.slug %}">
        <p class="catalogue-title" >{{object.titre}}</p>
        <div>{{object.description}}</div>
        <div><img style="object-fit: cover; width:100%;" src="{{object.image.url}}"></div>
      </a>
      <br>
    {% endfor %}

    {% include 'widgets/pagination.html' with page_obj=page_obj url='/catalogue/list' %}

  {% else %}
    Aucun document trouvé.

  {% endif %}


</div>


{% endblock content %}

mysite/catalogue/templates/catalogue/create_document.html
{% extends 'base.html' %}


{% block content %}

<div class="container">
  <h2 class='title'>Document
    <a class="bs-icon bi bi-caret-left" href="{% url 'catalogue:list' %}"></a>
  </h2>

  <form class="sticker" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'widgets/form.html' %}
    <button class='btn btn-primary' id='login' type="submit">Poster</button>
  </form>
</div>
{% endblock content %}

mysite/catalogue/templates/catalogue/detail_document.html
{% extends 'base.html' %}


{% block content %}

<div class="container">
  <h2 class="title">Document
    <a class="bs-icon bi bi-caret-left" href="{% url 'catalogue:list' %}"></a>
  </h2>

  <div class="sticker">
    <form method="POST" action="{% url 'catalogue:delete' object.slug %}">
      {% csrf_token %}

      <p class="catalogue-title">{{object.titre}}</p>
      <div>{{object.description}}</div>
      <a href="{% url 'catalogue:image' object.slug %}">
        <img style="object-fit: cover; width:100%;" src="{{object.image.url}}">
      </a>
      <div>Par @{{object.author}}, le {{object.date_published}}</div>

      {% if object.author == request.user %}
        <a href="{% url 'catalogue:edit' object.slug %}" class="btn btn-primary">Modifier</a>
        <input type="submit" class="btn btn-danger" onclick="return confirm('Etes vous sûr de vouloir supprimer ce document ?');" value="Supprimer">
      {% endif %}
    </form>
  </div>
</div>



{% endblock content %}

mysite/catalogue/templates/catalogue/edit_document.html
{% extends 'base.html' %}


{% block content %}

<div class="container">
  <h2 class='title'>Document
    <a class="bs-icon bi bi-caret-left" href="{% url 'catalogue:detail' object.slug %}"></a>

  </h2>

  <form  class="sticker" method="post"  enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'widgets/form.html' %}
    <br>
    <button class='btn btn-primary' id='login' type="submit">Mettre à jour</button>
  </form>
</div>



{% endblock content %}

mysite/catalogue/templates/catalogue/image.html
<!-- <!DOCTYPE html> -->
<html lang=fr>

  <head>
    <title> MySite </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>

    {% include 'colors.html' %}

    <style type="text/css">
      body {
        overflow: hidden;
        background-color: var(--page-bg);
      }

      #navigator {
        z-index: 2;
        position: absolute;
        left: 50%;
        transform: translate(-50%, 00%);
      }

      #img-container {
        z-index: 1;
        cursor: grab;
        position: absolute;
        text-align: center;
        background-color: blue;
      }

      #img {
        object-fit: cover
      }
    </style>

    <a class="btn btn-secondary" style="float: left;" href="{% url 'catalogue:detail' object.slug %}"> < </a>


    <div id="navigator">

      <div class="btn-group" role="group">
        <label class='btn btn-primary disabled'>Vitesse zoom </label>
        <button type="button" class="btn btn-primary" onclick="updateZoomStep(-100)">-</button>
        <label id="zoomStep" class='btn btn-primary disabled'> 200 </label>
        <button type="button" class="btn btn-primary" onclick="updateZoomStep(100)">+</button>
      </div>

      <button type="button" class="btn btn-primary" onclick="recenter()">Recentrer</button>


    </div>

    <div id="img-container">
      <img id="img" src="{{object.image.url}}">
    </div>

    <script type="text/javascript">
      const minWidth = 50;
      const imgRatio = 0.8;
      let zoomStep = 200;


      const img = document.getElementById("img");
      const container = document.getElementById("img-container");
      
      recenter();
      zoomElement();
      dragElement(document.getElementById("img-container"));
      updateZoomStep(0);


      function updateZoomStep(dstep) {
        zoomStep += dstep;
        if (zoomStep < 0) {
          zoomStep = 1;
        }
        document.getElementById('zoomStep').innerHTML = zoomStep;
      }

      function zoomElement() {
        let newWidth = 0;
        img.onmousewheel = zoom;

        function zoom(e) {
          if (e.wheelDelta > 0) {
            newWidth = (img.clientWidth + zoomStep);

          }
          else {
            newWidth = (img.clientWidth - zoomStep);

            // prevent too small images
            if (newWidth < minWidth) {
              newWidth = minWidth;
            }
          }

          let ratio = newWidth / img.clientWidth;
          img.style.width = newWidth + "px";

          // move image to focus zoom on mouse position
          container.style.left = (1-ratio) * e.pageX + ratio * container.offsetLeft;
          container.style.top = (1-ratio) * e.pageY + ratio * container.offsetTop;

        }
      }


      function dragElement() {
        var pos1 = 0, pos2 = 0, pos3 = 0, pos4 = 0;

        container.onmousedown = dragMouseDown;

        function dragMouseDown(e) {
          container.style.cursor = 'grabbing';

          e = e || window.event;
          e.preventDefault();
          pos3 = e.clientX;
          pos4 = e.clientY;
          document.onmouseup = closeDragElement;
          document.onmousemove = elementDrag;
        }


        function elementDrag(e) {

          e = e || window.event;
          e.preventDefault();
          pos1 = pos3 - e.clientX;
          pos2 = pos4 - e.clientY;
          pos3 = e.clientX;
          pos4 = e.clientY;
          container.style.top = (container.offsetTop - pos2) + "px";
          container.style.left = (container.offsetLeft - pos1) + "px";
        }



        function closeDragElement() {
          container.style.cursor = 'grab';
          document.onmouseup = null;
          document.onmousemove = null;
        }
      }

      function recenter() {
        let maxWidth = Math.floor(imgRatio * window.innerWidth);
        let maxHeight = Math.floor(imgRatio * window.innerHeight);

        if (maxHeight / maxWidth < img.clientHeight / img.clientWidth ) {
          maxWidth = maxHeight * img.clientWidth / img.clientHeight;
        }

        img.style.width =  maxWidth + "px";
        container.style.left = Math.floor(0.5 * (window.innerWidth - img.clientWidth)) + "px";
        container.style.top = Math.floor(0.5 * (window.innerHeight - img.clientHeight)) + "px";
      }


    </script>

  </body>

</html>