mysite/account/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView, PasswordChangeView
from django.urls import path

from .views import AccountDeleteView, AccountUpdateView, SigninView, SignupView

app_name = "account"


urlpatterns = [
    path(
        "login/", SigninView.as_view(template_name="account/login.html"), name="login"
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", SignupView.as_view(), name="signup"),
    path("update/", AccountUpdateView.as_view(), name="update"),
    path("<pk>/delete/", AccountDeleteView.as_view(), name="delete"),
    path(
        "password/",
        PasswordChangeView.as_view(template_name="account/change_password.html"),
        name="password",
    ),
]

mysite/blog/urls.py
from blog.views import (BlogListView, CreateBlogView, DeleteBlogView,
                        DetailBlogView, EditBlogView)
from django.urls import path

app_name = "blog"

urlpatterns = [
    path("list/", BlogListView.as_view(), name="list"),
    path("create/", CreateBlogView.as_view(), name="create"),
    path("<slug>/", DetailBlogView.as_view(), name="detail"),
    path("<slug>/edit/", EditBlogView.as_view(), name="edit"),
    path("<slug>/delete/", DeleteBlogView.as_view(), name="delete"),
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from personal.views import HomePageView  # home_screen_view

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("admin/", admin.site.urls),
    path("personal/", include("personal.urls", "personal")),
    path("account/", include("account.urls", "account")),
    path("blog/", include("blog.urls", "blog")),
    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path(
        "password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="registration/password_change_done.html"
        ),
        name="password_change_done",
    ),
    path(
        "password_change/",
        auth_views.PasswordChangeView.as_view(
            template_name="registration/password_change.html"
        ),
        name="password_change",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="registration/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/", auth_views.PasswordResetView.as_view(), name="password_reset"
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="registration/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/personal/urls.py
from django.urls import path

from .views import ContactView, download_data_view, generate_pdf_view

app_name = "personal"

urlpatterns = [
    path("contact/", ContactView.as_view(), name="contact"),
    path("pdf/", generate_pdf_view, name="pdf"),
    path("data/", download_data_view, name="data"),
]

mysite/personal/views.py
import copy
from io import BytesIO

import pandas as pd
from account.models import Account
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic.base import TemplateView

from .utils import generate_pdf

# nom du fichier de données téléchargé
EXCEL_FILENAME = "data.xlsx"
EXCEL_ENCODING = "utf8"


class HomePageView(LoginRequiredMixin, TemplateView):

    template_name = "personal/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["accounts"] = (
            list(Account.objects.values("id", "username", "email", "last_login")) * 100
        )
        categories = {
            "Catégorie 1": {
                "Sous-catégorie 1": {
                    "poppers": "#",
                    "tripe à la mode de caen": {"triptease 1": "#", "yeah": "#"},
                },
                "Sous-catégorie 2": "#",
            },
            "Catégorie 2": "#",
        }
        context["sidebar_menu"] = {"Catégories": categories}

        return context


class ContactView(LoginRequiredMixin, TemplateView):

    template_name = "personal/contact.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context[
            "contact_text"
        ] = "Bonjour;Je suis Sébastien votre assistant.;Si vous recherchez un contact je peux vous tâter.;Sinon nique ta mère;"
        return context


@login_required(login_url="login")
def generate_pdf_view(request):
    context = {}
    return generate_pdf(
        "personal/pdf_template.html",
        context,
        f"file_name.pdf",
        download=False,
    )


@login_required(login_url="login")
def download_data_view(request):
    df = pd.DataFrame()
    df.loc["row", "col"] = "Exemple"
    excel_file = BytesIO()
    xlwriter = pd.ExcelWriter(excel_file, engine="xlsxwriter")
    df.to_excel(xlwriter, "sheetname", encoding=EXCEL_ENCODING)
    xlwriter.save()
    xlwriter.close()
    excel_file.seek(0)
    response = HttpResponse(
        excel_file.read(),
        content_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    )
    response["Content-Disposition"] = "attachment; filename=" + EXCEL_FILENAME
    return response

mysite/personal/templates/personal/artist.html
{% extends 'base.html' %}
{% block content %}

<h1  class='title'>L'artiste</h1>


{% endblock content %}

mysite/personal/templates/personal/association.html
{% extends 'base.html' %}

{% block content %}

<h1  class='title'>L'association</h1>
{% if not request.user.is_authenticated %}
  <a class="btn btn-primary" href="{% url 'account:login' %}">Se connecter</a>
{% endif %}

{% endblock content %}

mysite/personal/templates/personal/contact.html
{% extends 'base.html' %}

{% block content %}
  {% include 'widgets/readme_typing.html' with text=contact_text %}

{% endblock content %}

mysite/personal/templates/personal/home.html
{% extends 'base.html' %}

{% block content %}


<div class="container">
  <h2 class='title'>Boite de réception</h2>
  {% if user %}
    <p> {{ user }} connecté </p>
  {% endif %}

  <a href="{% url 'personal:pdf' %}" class="btn bs-icon2 bi-file-medical"></a>
  <a href="{% url 'personal:data' %}" class="btn bs-icon1 bi-file-earmark-ruled" ></a>

  <div id="table">
    {% include 'widgets/table.html' with table=accounts %}
  </div>
</div>


{% endblock content %}

mysite/personal/templates/personal/pdf_template.html
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

{% load static %}
<style type="text/css">
  .body {
    font-family: georgia;
  }

  .logo {
    margin-right: 30px;
    width: 200px;
    float: right;
  }

  .body {
    margin: 0px auto;
    padding-top: 150px;
    width: 75%;
  }

  .h {
    font-weight: bold;
    width: 220px;
  }

  h1 {
    text-align: center;
  }

  .table-borderless>tbody,
  .table-borderless>tbody>tr,
  .table-borderless>tbody>tr>td {
    border: none;
  }
</style>

<br>
<div class="header">
  <img class="logo" src="{{SERVER_URL}}static/images/logo_erasme.png" alt="logo erasme">
</div>

<div class="body">

  <div class="title">
    <h1> Modifications des traitements </h1>
  </div>
  <br><br>

  <h2> Patient </h2>
  <hr>
  <table class="table table-borderless" id="info">
    <tbody>
      <tr>
        <td class='h'>Nom :</td>
        <td>{{patient.lastname}}</td>
      </tr>
      <tr>
        <td class='h'>Prénom :</td>
        <td>{{patient.firstname}}</td>
      </tr>
      <tr>
        <td class='h'>Date de naissance :</td>
        <td>{{patient.ddn | date:'d/m/Y'}}</td>
      </tr>
      <tr>
        <td class='h'>Poids :</td>
        <td>{% if patient.weight %}{{patient.weight}} kg{% endif %}</td>
      </tr>
      <tr>
        <td class='h'>Taille :</td>
        <td>{% if patient.height %}{{patient.height}} cm {% endif %}</td>
      </tr>
    </tbody>
  </table>
  <br><br>

  <h2> Intervention </h2>
  <hr>
  <table class="table table-borderless" id="intervention">
    <tbody>
      <tr>
        <td class='h'>Nom du chirurgien :</td>
        <td>{{patient.chirurgien}}</td>
      </tr>
      <tr>
        <td class='h'>Type de chirurgie :</td>
        <td>{{patient.chirurgie}}</td>
      </tr>
      <tr>
        <td class='h'>Date de la chirurgie :</td>
        <td>{{patient.ddi | date:'d/m/Y'}}</td>
      </tr>
    </tbody>
  </table>
  <br><br>

  <h2> Consultation </h2>
  <hr>
  <table class="table table-borderless" id="consultation">
    <tbody>
      <tr>
        <td class='h'>Médecin :</td>
        <td>{{patient.author.alias}}</td>
      </tr>
      <tr>
        <td class='h'>Date de la consultation :</td>
        <td>{{patient.ddconsult | date:'d/m/Y'}}</td>
      </tr>
    </tbody>
  </table>
  <br><br>

  <h2> Modifications à faire (algorithme {{patient.algo}}) </h2><br>

  <table class="table " id="result">
    <thead>
      <th>Traitements</th>
      <th>Modalités d'interruption</th>
    </thead>

    <tbody>

      {% for v in patient.traitements.values %}
      <tr>
        <td>{{v.traitement}}</td>
        <td>
          {% for concl in v.conclusion %}
          <a>{{concl}}</a><br>
          {% endfor %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>


</div>