mysite/account/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView, PasswordChangeView
from django.urls import path

from .views import AccountDeleteView, AccountUpdateView, SigninView, SignupView

app_name = "account"


urlpatterns = [
    path(
        "login/", SigninView.as_view(template_name="account/login.html"), name="login"
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", SignupView.as_view(), name="signup"),
    path("update/", AccountUpdateView.as_view(), name="update"),
    path("<pk>/delete/", AccountDeleteView.as_view(), name="delete"),
    path(
        "password/",
        PasswordChangeView.as_view(template_name="account/change_password.html"),
        name="password",
    ),
]

mysite/blog/urls.py
from blog.views import (BlogListView, CreateBlogView, DeleteBlogView,
                        DetailBlogView, EditBlogView)
from django.urls import path

app_name = "blog"

urlpatterns = [
    path("list/", BlogListView.as_view(), name="list"),
    path("create/", CreateBlogView.as_view(), name="create"),
    path("<slug>/", DetailBlogView.as_view(), name="detail"),
    path("<slug>/edit/", EditBlogView.as_view(), name="edit"),
    path("<slug>/delete/", DeleteBlogView.as_view(), name="delete"),
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from personal.views import HomePageView  # home_screen_view

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("admin/", admin.site.urls),
    path("personal/", include("personal.urls", "personal")),
    path("account/", include("account.urls", "account")),
    path("blog/", include("blog.urls", "blog")),
    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path(
        "password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="registration/password_change_done.html"
        ),
        name="password_change_done",
    ),
    path(
        "password_change/",
        auth_views.PasswordChangeView.as_view(
            template_name="registration/password_change.html"
        ),
        name="password_change",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="registration/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/", auth_views.PasswordResetView.as_view(), name="password_reset"
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="registration/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/personal/urls.py
from django.urls import path

from .views import ContactView, download_data_view, generate_pdf_view

app_name = "personal"

urlpatterns = [
    path("contact/", ContactView.as_view(), name="contact"),
    path("pdf/", generate_pdf_view, name="pdf"),
    path("data/", download_data_view, name="data"),
]

mysite/templates/snippets/header_menu.html
<style type="text/css">
  .htext-secondary {
    color: var(--head-txt2);
  }
  .htext-primary {
    color: var(--head-txt1);
  }
</style>

<a class="nav-link px-2 htext-secondary" href="{% url 'home' %}">Accueil</a>
{% if user.is_staff %}
<a class="nav-link px-2 htext-primary" href="/admin/">Administration</a>
{% endif %}
<a class="nav-link px-2 htext-primary" href="{% url 'personal:contact' %}">Contact</a>

mysite/templates/snippets/profile_menu.html
<li><a class="dropdown-item" href="{% url 'account:update' %}">Mon compte</a></li>
<li><hr class="dropdown-divider"></li>
<li><a class="dropdown-item" href="{% url 'account:logout' %}">Se déconnecter</a></li>

mysite/templates/snippets/sidebar_menu.html
<a href="{% url 'account:update' %}" id="sb-btn" class='btn text-left btn-block' style="fontsize:17px;padding-left:10px;" >
  Mon compte</a>
<a href="{% url 'blog:list' %}" id="sb-btn" class='btn text-left btn-block' style="fontsize:17px;padding-left:10px;" >
  Fil d'actualité</a>
<a href="{% url 'blog:create' %}" id="sb-btn" class='btn text-left btn-block' style="fontsize:17px;padding-left:10px;" >
  Publier</a>
<a href="{% url 'home' %}" id="sb-btn" class='btn text-left btn-block' style="fontsize:17px;padding-left:10px;" >
  Boite de réception</a>

<hr class="sidebar-divider">