mysite/blog/urls.py
from blog.views import (BlogListView, CreateBlogView, DeleteBlogView,
                        DetailBlogView, EditBlogView)
from django.urls import path

app_name = "blog"

urlpatterns = [
    path("list/", BlogListView.as_view(), name="list"),
    path("create/", CreateBlogView.as_view(), name="create"),
    path("<slug>/", DetailBlogView.as_view(), name="detail"),
    path("<slug>/edit/", EditBlogView.as_view(), name="edit"),
    path("<slug>/delete/", DeleteBlogView.as_view(), name="delete"),
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from personal.views import HomePageView  # home_screen_view

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("admin/", admin.site.urls),
    path("personal/", include("personal.urls", "personal")),
    path("account/", include("account.urls", "account")),
    path("blog/", include("blog.urls", "blog")),
    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path(
        "password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="registration/password_change_done.html"
        ),
        name="password_change_done",
    ),
    path(
        "password_change/",
        auth_views.PasswordChangeView.as_view(
            template_name="registration/password_change.html"
        ),
        name="password_change",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="registration/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/", auth_views.PasswordResetView.as_view(), name="password_reset"
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="registration/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/blog/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import post_delete, pre_save
from django.dispatch import receiver
from django.utils.text import slugify


def upload_location(instance, filename):
    file_path = "blog/{author_id}/{title}-{filename}".format(
        author_id=str(instance.author.id), title=str(instance.title), filename=filename
    )
    return file_path


class BlogPost(models.Model):
    title = models.CharField(max_length=50, null=False, blank=False)
    body = models.TextField(max_length=5000, null=False, blank=True)
    image = models.ImageField(upload_to=upload_location, null=True, blank=True)
    date_published = models.DateTimeField(
        auto_now_add=True, verbose_name="date published"
    )
    date_updated = models.DateTimeField(auto_now=True, verbose_name="date updated")
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    slug = models.SlugField(blank=True, unique=True)

    def __str__(self):
        return self.title

    def get_fields(self):
        return [
            (field.verbose_name, field.value_from_object(self))
            for field in self.__class__._meta.fields
        ]


@receiver(post_delete, sender=BlogPost)
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False)


def pre_save_blog_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.author.username + "-" + instance.title)


pre_save.connect(pre_save_blog_post_receiver, sender=BlogPost)

mysite/blog/forms.py
from blog.models import BlogPost
from django import forms

from mysite.widgets import MyCroppieField

IMG_OPTIONS = {
    "viewport": {"width": 180, "height": 180, "shape": "square"},
}


class BlogPostForm(forms.ModelForm):
    image = MyCroppieField(label="", options=IMG_OPTIONS, required=False)

    class Meta:
        model = BlogPost
        fields = ["title", "body", "image"]

mysite/blog/views.py
from account.models import Account
from blog.forms import BlogPostForm
from blog.models import BlogPost
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView


class CreateBlogView(LoginRequiredMixin, CreateView):
    form_class = BlogPostForm
    template_name = "blog/create_blog.html"

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = Account.objects.filter(
            username=self.request.user.username
        ).first()
        self.object.save()
        return redirect("blog:list")


class EditBlogView(LoginRequiredMixin, UpdateView):
    model = BlogPost
    fields = ["title", "body", "image"]
    template_name = "blog/edit_blog.html"

    def dispatch(self, request, *args, **kwargs):
        object = self.get_object()
        if request.user != object.author:
            return redirect("blog:detail", object.slug)
        return UpdateView.dispatch(self, request, *args, **kwargs)

    def form_valid(self, form):
        self.object = form.save()
        return self.render_to_response(self.get_context_data(form=form))


class DetailBlogView(LoginRequiredMixin, DetailView):
    model = BlogPost
    template_name = "blog/detail_blog.html"


class BlogListView(LoginRequiredMixin, ListView):
    model = BlogPost
    paginate_by = 20
    template_name = "blog/list_blog.html"
    ordering = ["-date_published"]


class DeleteBlogView(DeleteView):
    model = BlogPost
    success_url = "/blog/list"

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

mysite/blog/templates/blog/create_blog.html
{% extends 'base.html' %}


{% block content %}

<div class="container">
  <h2 class='title'>Post
    <a class="bs-icon bi bi-caret-left" href="{% url 'blog:list' %}"></a>
  </h2>

  <form class="sticker" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'widgets/form.html' %}
    <button class='btn btn-primary' id='login' type="submit">Poster</button>
  </form>
</div>
{% endblock content %}

mysite/blog/templates/blog/detail_blog.html
{% extends 'base.html' %}


{% block content %}

<div class="container">
  <h2 class="title">Post
    <a class="bs-icon bi bi-caret-left" href="{% url 'blog:list' %}"></a>
  </h2>

  <div class="sticker">
    <form method="POST" action="{% url 'blog:delete' object.slug %}"> {% csrf_token %}

    <p class="blog-title">{{object.title}}</p>
    <div>{{object.body}}</div>
    <div><img style="object-fit: cover; width:100%;" src="{{object.image.url}}"></div>
    <div>Par @{{object.author}}, le {{object.date_published}}</div>

    {% if object.author == request.user %}
      <a href="{% url 'blog:edit' object.slug %}" class="btn btn-primary">Modifier</a>
      <input type="submit" class="btn btn-danger" onclick="return confirm('Etes vous sûr de vouloir supprimer ce post ?');" value="Supprimer">
    {% endif %}
  </div>
</div>



{% endblock content %}

mysite/blog/templates/blog/edit_blog.html
{% extends 'base.html' %}


{% block content %}

<div class="container">
  <h2 class='title'>Post
    <a class="bs-icon bi bi-caret-left" href="{% url 'blog:detail' object.slug %}"></a>

  </h2>

  <form  class="sticker" method="post"  enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'widgets/form.html' %}
    <br>
    <button class='btn btn-primary' id='login' type="submit">Mettre à jour</button>
  </form>
</div>



{% endblock content %}

mysite/blog/templates/blog/list_blog.html
{% extends 'base.html' %}


{% block content %}

<div class="container">
  <h2 class='title'>Posts
    <a class="bs-icon bi bi-file-plus" href="{% url 'blog:create' %}"></a>
  </h2>


  {% if object_list %}
    {% for object in object_list %}
      <div class="sticker">
        <a class="btn" style="width:100%;" href="{% url 'blog:detail' object.slug %}">
          <p class="blog-title" >{{object.title}}</p>
          <div>{{object.body}}</div>
          <div><img style="object-fit: cover; width:100%;" src="{{object.image.url}}"></div>
        </a>
      </div>
      <br>
    {% endfor %}

    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="/blog/list?page={{ page_obj.previous_page_number }}">précédent</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} sur {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="/blog/list?page={{ page_obj.next_page_number }}">suivant</a>
                {% endif %}
            </span>
        </div>
    {% endif %}

  {% else %}
    Aucun post.
  {% endif %}
</div>

{% endblock content %}